package sistemavotacion;

import javax.swing.DefaultComboBoxModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import clases.*;
import TDAA.*;
import javax.swing.JOptionPane;

public class FormVotacion extends javax.swing.JFrame {
    private Sistema sistema;
    private Participante participanteActual; 
    private DefaultComboBoxModel modeloComboCandidatos;
    private DefaultComboBoxModel modeloComboMesas;
     private DefaultComboBoxModel modeloComboeleccion;
     private Lista<Candidato> listaCandidatos;
     private Lista<MesaElectoral> mesas;
     private Lista<Eleccion> listaEleccion;
   
  

    public FormVotacion(Sistema sistema, Participante participanteActual){
        initComponents();
        this.sistema = sistema;
        this.participanteActual = participanteActual;
        modeloComboCandidatos = new DefaultComboBoxModel();
         modeloComboMesas = new DefaultComboBoxModel();
       modeloComboeleccion = new DefaultComboBoxModel();
        this.listaCandidatos = sistema.obtenerCandidato();
        this.mesas=sistema.getListaMesas();
        this.listaEleccion=sistema.obtenereleccion();
        inicializarComboBox();
        cargarTiposDeVoto();
        inicializarFecha();
        inicializarComboBox1();
        inicializarComboBox2();
        
    }

    public FormVotacion(){
        initComponents();
    
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String horaActual = dateFormat.format(new Date());
        txtFechaEleccion.setText(horaActual);
        txtFechaEleccion.setEditable(false);
    }

    private void inicializarFecha() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String horaActual = dateFormat.format(new Date());
        txtFechaEleccion.setText(horaActual);
        txtFechaEleccion.setEditable(false);
    }


private void inicializarComboBox() {
    modeloComboMesas = new DefaultComboBoxModel<>();

    for (int i = 1; i <= mesas.longitud(); i++) {
        MesaElectoral mesa= mesas.iesimo(i);
  
        String numeroYubicacion = mesa.getNumeroMesa() + " (" + mesa.getUbicacion() + ")";
        modeloComboMesas.addElement(numeroYubicacion);
    }
    cboMesa.setModel(modeloComboMesas);
}
 
 
  private void inicializarComboBox1() {
    modeloComboCandidatos = new DefaultComboBoxModel<>();

    for (int i = 1; i <= listaCandidatos.longitud(); i++) {
        Candidato candidato = listaCandidatos.iesimo(i);
  
        String nombreYPartidoPolitico = candidato.getNombre() + " (" + candidato.getPartidoPolitico() + ")";
        modeloComboCandidatos.addElement(nombreYPartidoPolitico);
    }
    cboCandidato.setModel(modeloComboCandidatos);
}
  private void inicializarComboBox2() {
    modeloComboeleccion = new DefaultComboBoxModel<>();

    for (int i = 1; i <= listaEleccion.longitud(); i++) {
        Eleccion eleccion = listaEleccion.iesimo(i);
  
        String tipo = eleccion.getTipo();
        modeloComboeleccion.addElement(tipo);
    }
    cboTipoeleccion.setModel(modeloComboeleccion);
}






    private void cargarTiposDeVoto() {
        cmbTipoVoto.addItem("Preferencial");
        cmbTipoVoto.addItem("No preferencial");
     
    }

   

    private TIPOVOTO obtenerTipoVoto(String tipoVotoStr) {
        switch (tipoVotoStr) {
            case "Preferencial":
                return TIPOVOTO.VALIDO;
            case "Blanco":
                return TIPOVOTO.EN_BLANCO;
            case "Nulo":
                return TIPOVOTO.NULO;
            default:
                throw new IllegalArgumentException("Tipo de voto no reconocido");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipoVoto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFechaEleccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboCandidato = new javax.swing.JComboBox<>();
        cboTipoeleccion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboMesa = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbTipoVoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVotoActionPerformed(evt);
            }
        });

        jLabel1.setText("Votaciones");

        jLabel2.setText("Candidato:");

        jLabel3.setText("Tipo de voto:");

        btnGuardar.setText("Enviar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha y hora de elección:");

        txtFechaEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEleccionActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de elección:");

        cboTipoeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoeleccionActionPerformed(evt);
            }
        });

        jLabel6.setText("Mesa Electoral");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboTipoeleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaEleccion)
                            .addComponent(cboCandidato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoVoto, 0, 146, Short.MAX_VALUE)
                            .addComponent(cboMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboTipoeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoVotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoVotoActionPerformed

    private void txtFechaEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEleccionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 try {
        
        if (sistema.haVotado(participanteActual)) {
            JOptionPane.showMessageDialog(this, "Ya has emitido tu voto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; 
        }

   
        int indiceCandidato = cboCandidato.getSelectedIndex();
        int indiceMesa = cboMesa.getSelectedIndex();
        String tipoVotoStr = (String) cmbTipoVoto.getSelectedItem();

        if (indiceCandidato == -1 || indiceMesa == -1 || tipoVotoStr == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        Candidato candidatoSeleccionado = listaCandidatos.iesimo(indiceCandidato + 1); 
        MesaElectoral mesaSeleccionada = mesas.iesimo(indiceMesa + 1);
        TIPOVOTO tipoVoto = obtenerTipoVoto(tipoVotoStr);

        
        sistema.crearVoto(candidatoSeleccionado, mesaSeleccionada, tipoVoto, participanteActual);

        JOptionPane.showMessageDialog(this, "¡Tu voto ha sido registrado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        
        this.dispose(); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar el voto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cboTipoeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoeleccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboCandidato;
    private javax.swing.JComboBox<String> cboMesa;
    private javax.swing.JComboBox<String> cboTipoeleccion;
    private javax.swing.JComboBox<String> cmbTipoVoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFechaEleccion;
    // End of variables declaration//GEN-END:variables
}
