/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemavotacion;
import clases.MiembroDeMesa;
import clases.Sistema;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
public class ListadeMiembrosdeMesa extends javax.swing.JFrame {

     
    private Sistema registromiembrosdemesas;
    private DefaultTableModel modeloTabla2;
   

    
    public ListadeMiembrosdeMesa(Sistema registromiembrosdemesas) {
        initComponents();
        modeloTabla2 = new DefaultTableModel();
        this.registromiembrosdemesas = registromiembrosdemesas;
        this.tablalistamiembros.setModel(modeloTabla2);
        modeloTabla2.addColumn("Nombres");
        modeloTabla2.addColumn("Apellidos");
         modeloTabla2.addColumn("Tipo deleccion");
         modeloTabla2.addColumn("Clave de acceso");
        actualizarTabla();
    }

    
              
    
    private void actualizarTabla(){
        
         int numFilas = modeloTabla2.getRowCount();
        for (int i = numFilas-1; i >= 0; i--) {
            modeloTabla2.removeRow(i);
        }
        MiembroDeMesa[] listaMiembrodemesa = this.registromiembrosdemesas.getListaMiembrodeMesa();
        for (int i = 0; i < listaMiembrodemesa.length; i++) {
              MiembroDeMesa objMiembro = listaMiembrodemesa[i];
    
               String[] fila = new String[4];
                 fila[0] = objMiembro.getNombre();
                 fila[1] = objMiembro.getApellido();
                 fila[2] = objMiembro.getTipo();  
                 fila[3] = objMiembro.getClaveAcceso();
                
                 
                 
    modeloTabla2.addRow(fila);
}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistamiembros = new javax.swing.JTable();
        btnModificar = new javax.swing.JToggleButton();
        btnCerrar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFila = new javax.swing.JTextField();
        txtNuevoDato = new javax.swing.JTextField();
        txtColumna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Miembros de Mesa");

        tablalistamiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablalistamiembros);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Fila:");

        jLabel3.setText("Columna:");

        jLabel4.setText("Nuevo Dato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNuevoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnEliminar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtNuevoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar)
                    .addComponent(jLabel3)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int filaSeleccionada = this.tablalistamiembros.getSelectedRow();
if (filaSeleccionada >= 0) {
    int result = JOptionPane.showConfirmDialog(rootPane, "¿Estás seguro de eliminar?");

    if (result == 0) {
        String dni = modeloTabla2.getValueAt(filaSeleccionada, 2).toString();  
        this.registromiembrosdemesas.eliminar(dni);  

        actualizarTabla();
        JOptionPane.showMessageDialog(this, "¡Eliminado correctamente!");
    }
} else {
    JOptionPane.showMessageDialog(this, "¡No seleccionaste un registro!");
}          
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
      dispose();        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
  try {
   
        int fila = Integer.parseInt(txtFila.getText());
        int columna = Integer.parseInt(txtColumna.getText());
        String nuevoDato = txtNuevoDato.getText();

        
        if (fila >= 0 && fila < modeloTabla2.getRowCount() && columna >= 0 && columna < modeloTabla2.getColumnCount()) {
            // Actualizar el modelo de la tabla
            modeloTabla2.setValueAt(nuevoDato, fila, columna);

          
            MiembroDeMesa miembro = this.registromiembrosdemesas.getListaMiembrodeMesa()[fila];
            switch (columna) {
                case 0:
                    miembro.setNombre(nuevoDato); 
                    break;
                case 1:
                    miembro.setApellido(nuevoDato); 
                    break;
                case 2:
                    miembro.setTipo(nuevoDato); 
                    break;
                case 3:
                    miembro.setClaveAcceso(nuevoDato); 
                    break;
                default:
                    throw new IllegalArgumentException("Columna no válida.");
            }

          
            JOptionPane.showMessageDialog(this, "¡Modificación guardada correctamente!");
        } else {
            JOptionPane.showMessageDialog(this, "Índices fuera de rango. Verifica los valores ingresados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa números válidos para fila y columna.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

             
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
   
                
    

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCerrar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablalistamiembros;
    private javax.swing.JTextField txtColumna;
    private javax.swing.JTextField txtFila;
    private javax.swing.JTextField txtNuevoDato;
    // End of variables declaration//GEN-END:variables
}
